In [17]:
import pandas as pd
from sklearn.preprocessing import LabelEncoder
le=LabelEncoder()
from sklearn.linear_model import LinearRegression

In [8]:
df=pd.read_csv("one hot Encoding.csv")
df

               town  area   price
0   monroe township  2600  550000
1   monroe township  3000  565000
2   monroe township  3200  610000
3   monroe township  3600  680000
4   monroe township  4000  725000
5      west windsor  2600  585000
6      west windsor  2800  615000
7      west windsor  3300  650000
8      west windsor  3600  710000
9       robinsville  2600  575000
10      robinsville  2900  600000
11      robinsville  3100  620000
12      robinsville  3600  695000

In [9]:
dfle=df
dfle.town=le.fit_transform(dfle.town)

In [10]:
dfle

    town  area   price
0      0  2600  550000
1      0  3000  565000
2      0  3200  610000
3      0  3600  680000
4      0  4000  725000
5      2  2600  585000
6      2  2800  615000
7      2  3300  650000
8      2  3600  710000
9      1  2600  575000
10     1  2900  600000
11     1  3100  620000
12     1  3600  695000

In [23]:
x=dfle.drop(['price'],axis='columns')
#y=dfle.price
x

    town  area
0      0  2600
1      0  3000
2      0  3200
3      0  3600
4      0  4000
5      2  2600
6      2  2800
7      2  3300
8      2  3600
9      1  2600
10     1  2900
11     1  3100
12     1  3600

In [24]:
from sklearn.preprocessing import OneHotEncoder

In [45]:
from sklearn.preprocessing import OneHotEncoder
from sklearn.compose import ColumnTransformer

# Assuming your categorical column is the first one (index 0)
ct = ColumnTransformer(
    transformers=[('encoder', OneHotEncoder(), [0])], 
    remainder='passthrough'
)

TypeError: OneHotEncoder.__init__() got an unexpected keyword argument 'sparse'

In [44]:
x = ct.fit_transform(x).toarray()

TypeError: Sparse data was passed, but dense data is required. Use '.toarray()' to convert to a dense numpy array.